extends Resource
class_name SoundEffectSettings

enum SOUND_EFFECT_LABEL{
	BATTLE_A,
	BATTLE_MEDIEVAL,
	LOBBYJAM,
	VICTORY,
	SFX_ARROWSHOOT,
	SFX_BOBDIE,
	SFX_COLLECTGOLD,
	SFX_ENEMYSPAWN,
	SFX_GRASSWALK,
	SFX_HEARTDESTROY,
	SFX_HEARTHIT,
	SFX_HEAVYHIT,
	SFX_LIGHTHIT,
	SFX_SLIMELAND,
	SFX_STARTVICTORY,
	SFX_SWORDHITENEMY,
	SFX_SWORDHITTOWER,
	SFX_TOWERBUILD,
	SFX_TOWERFALL,
	SFX_UICLICK,
	SFX_UIHOVER,
	SFX_UIPLACETOWER
}

@export var label : SOUND_EFFECT_LABEL
@export var stream : AudioStream
@export_range(-40,24) var volume : float = 1.0
@export_range(0.01, 4.0) var pitch : float = 1.0
